In [39]:
#1) Create numpy array and perform following operation 
# > Convert 1D array to 2D 
# > Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
# > Create a 3×3 NumPy array of all 9 
# > Create a 1D array of 10 evenly spaced values between 25 and 125 
# > Convert a Python list into a NumPy array 
# > Reverse a 1D NumPy array 
# > Create a 4×4×3 array and extract value at its second set, first row and last column 
# > Create a 4×4 and Extract Odd Rows and Even Columns 
# > Slice the first two rows and first two columns of econd set from a 4×4×3 array 
# > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] 
# > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
# > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. 
# > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]


import numpy as np
arr = np.array([1,2,3,4,5,6])
result = arr.reshape(2,3)
print(result,"\n")
r1 = arr.reshape(6,1)
print(r1)


print(result.shape)
print(result.ndim)
print(result.dtype)
print(result.itemsize)


arr2 = np.full((3,3),9)
print(arr2)
r2 = np.ones((3,3),dtype=int)*9
print(r2)


arr3 = np.linspace(25,125,10)
print(arr3)
r3 = np.arange(25,125,10)
print(r3)


l1 = [12,13,14,15,16,18]
arr4 = np.array(l1)
print(arr4)


result2 = arr4[::-1]
print(result2)


arr5 = np.array([[[11,12,13,14],
                  [15,16,17,18],
                  [19,20,21,22],
                  [23,24,25,26]],
                 [[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]],
                 [[31,32,33,34],
                  [35,36,37,38],
                  [39,40,41,42],
                  [43,44,45,46]]])
print(arr5)
print(arr5[1,1,3])


arr6 = np.array([[11,12,13,14],
                  [15,16,17,18],
                  [19,20,21,22],
                  [23,24,25,26]])
result3 = arr6[::2,1::2]
print(result3)


print(arr5[1,0:2,0:2])


arr7 = np.array([[23, 56, 78, 93], [71, 82,13, 24]])
for i in range(arr7.shape[0]):
    for j in range(arr7.shape[1]):
        if (arr7[i][j]%2!=0):
            arr7[i][j]=-1
print(arr7)


arr8 = np.array([1, 0, 2, 0, 3, 0, 4])
l2 = []
for i in range(len(arr8)):
    if(arr8[i]!=0):
        l2.append(i)
print(l2)
    

arr9 = np.array( [[39,40,41,42],
                 [43,44,45,46],
                 [23, 56, 78, 93], 
                 [71, 82,13, 24]])
print(arr6+arr9) # normally it happens element by element
print(arr6*arr9)


arr10 = np.array([15,20,25])
arr11 = np.array([10,40,37])
dot_product = np.dot(arr10,arr11)
print(dot_product)
result4 = 0
for i in range(len(arr10)):
    result4+=arr10[i]*arr11[i]
print(result4)

[[1 2 3]
 [4 5 6]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(2, 3)
2
int64
8
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]
[ 25  35  45  55  65  75  85  95 105 115]
[12 13 14 15 16 18]
[18 16 15 14 13 12]
[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]
  [23 24 25 26]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[31 32 33 34]
  [35 36 37 38]
  [39 40 41 42]
  [43 44 45 46]]]
8
[[12 14]
 [20 22]]
[[1 2]
 [5 6]]
[[-1 56 78 -1]
 [-1 82 -1 24]]
[0, 2, 4, 6]
[[ 50  52  54  56]
 [ 58  60  62  64]
 [ 42  76  99 115]
 [ 94 106  38  50]]
[[ 429  480  533  588]
 [ 645  704  765  828]
 [ 437 1120 1638 2046]
 [1633 1968  325  624]]
1875
1875
