In [5]:
#1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 
import pandas as pd
import numpy as np
arr = np.array([[6,-8,73,-110],[np.nan,-8,0,94]])
print(arr)
#replacing nan with zero
arr[np.isnan(arr)] = 0
print(arr)
arr[:,[0,2]] = arr[:,[2,0]]
arr[:,[1,3]] = arr[:,[3,1]]
print(arr)

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[  73. -110.    6.   -8.]
 [   0.   94.    0.   -8.]]


In [11]:
#2) Move axes of 3D array to new positions
arr2 = np.zeros((3,4,5))
print(arr2)
print(arr2.shape)

result1 = np.moveaxis(arr2,0,-1)
print(result1.shape)

result2 = np.moveaxis(arr2,-1,0)
print(result2.shape)

result3 = np.moveaxis(arr2,[0,1],[1,0])
print(result3.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(3, 4, 5)
(4, 5, 3)
(5, 3, 4)
(4, 3, 5)


In [ ]:
#3) Replace NaN values with average of columns.
#4) Replace negative value with zero in numpy array using replace.

arr3 = np.array([[12,np.nan,45],[np.nan,22,87],[23,42,np.nan]])
print(arr3)

col_means = np.nanmean(arr3,axis=0)    # if axis is 0 then mean is calculated column wise and if axis is 1 then mean is calculated row wise
print(f"column means: {col_means}")
arr_filled = np.where(np.isnan(arr3),col_means,arr3)
print(arr_filled)

arr[arr<0] = 0
print(arr)       # swapped arr with replaced negative values

[[12. nan 45.]
 [nan 22. 87.]
 [23. 42. nan]]
column means: [17.5 32.  66. ]
[[12.  32.  45. ]
 [17.5 22.  87. ]
 [23.  42.  66. ]]
[[73.  0.  6.  0.]
 [ 0. 94.  0.  0.]]
