In [25]:
#1) Combining a one and a two-dimensional NumPy Array.
import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[11,12,13]])
arr2 = np.array([7,8,9])
print(arr1,"\n")
print(arr2)
result1 = np.vstack((arr1,arr2))
print("\n",result1)   # combines the arrays vertically and or row wise

result2 = np.column_stack((arr1,arr2))
print("\n",result2)  # this inserts the array as new column in the given array

result3 = np.concatenate((arr1,arr2.reshape(1,3)), axis=0)   # this also combines the array row wise but it first reshape the 1d array
print("\n",result3)

#2) Flatten a 2d numpy array into 1d array
result4 = arr1.reshape(-1)
print("\n",result4)

#3) Reverse a numpy array
result4 = result4[::-1]
print("\n",result4)        # reversing an array after flatting it then again reshape it as required 

result5 = arr1[::-1]
print("\n",result5)       # reversing an array as it is 

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]] 

[7 8 9]

 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [ 7  8  9]]

 [[ 1  2  3  7]
 [ 4  5  6  8]
 [11 12 13  9]]

 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [ 7  8  9]]

 [ 1  2  3  4  5  6 11 12 13]

 [13 12 11  6  5  4  3  2  1]

 [[11 12 13]
 [ 4  5  6]
 [ 1  2  3]]


In [42]:
#4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given 
# array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, 
# Subtracting, multiplying, dividing arrays in Numpy

arr3 = np.array([[12,324,41],
                 [34,453,23],
                 [89,676,87]])
max_element = np.max(arr3)
print(max_element)
min_element = np.min(arr3)
print(min_element)
print('rows:',arr3.shape[0])  
print('columns:',arr3.shape[1]) 

# accessing elements in the array
for i in arr3:
    for j in i:
        print(j)
        
# accessing the specfic element in the array
print(arr3[2][1])  # arr[row_index][column_index]

# adding array element by for loop
s = 0
for i in arr3:
    for j in i:
        s = s+j
        
print("Final sum of array is:",s)

676
12
rows: 3
columns: 3
12
324
41
34
453
23
89
676
87
676
Final sum of array is: 1739


In [43]:
# airthmatic operations on array
t = np.array([
    [[1,2,3,4],[2,3,4,6],[5,6,7,9],[7,4,9,4]],
    [[3,1,6,5],[6,3,4,7],[6,8,4,8],[6,2,3,1]]
])
s = np.array([
    [[1,2,3,4],[2,3,4,6],[5,6,7,9],[7,4,9,4]],
    [[2,1,5,3],[5,6,6,8],[4,8,1,9],[4,2,3,1]]
])
print(t+s)
print(t-s)
print(t/s)
print(t*s)
print(t)
print(s)
print(t**s)
res= np.mean(t,axis=2)   # similarly we can perform sum,median,mode,std,variance
print(res)

[[[ 2  4  6  8]
  [ 4  6  8 12]
  [10 12 14 18]
  [14  8 18  8]]

 [[ 5  2 11  8]
  [11  9 10 15]
  [10 16  5 17]
  [10  4  6  2]]]
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 1  0  1  2]
  [ 1 -3 -2 -1]
  [ 2  0  3 -1]
  [ 2  0  0  0]]]
[[[1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]]

 [[1.5        1.         1.2        1.66666667]
  [1.2        0.5        0.66666667 0.875     ]
  [1.5        1.         4.         0.88888889]
  [1.5        1.         1.         1.        ]]]
[[[ 1  4  9 16]
  [ 4  9 16 36]
  [25 36 49 81]
  [49 16 81 16]]

 [[ 6  1 30 15]
  [30 18 24 56]
  [24 64  4 72]
  [24  4  9  1]]]
[[[1 2 3 4]
  [2 3 4 6]
  [5 6 7 9]
  [7 4 9 4]]

 [[3 1 6 5]
  [6 3 4 7]
  [6 8 4 8]
  [6 2 3 1]]]
[[[1 2 3 4]
  [2 3 4 6]
  [5 6 7 9]
  [7 4 9 4]]

 [[2 1 5 3]
  [5 6 6 8]
  [4 8 1 9]
  [4 2 3 1]]]
[[[        1    

In [ ]:
# 5) Iterate 3D array using for loop and nditer
arr4 = np.array([
    [[1,2,3,4],[2,3,4,6],[5,6,7,9],[7,4,9,4]],
    [[3,1,6,5],[6,3,4,7],[6,8,4,8],[6,2,3,1]]
])
for i in arr4:
    for j in i:
        for k in j:
            print(k) # this returns each element of the array
            
print("\n","traversing using nditer")
            
for t in np.nditer(arr4):   # nditer function traverse all the dimension itself no need of nested loops to increase time complexity
    print(t)

1
2
3
4
2
3
4
6
5
6
7
9
7
4
9
4
3
1
6
5
6
3
4
7
6
8
4
8
6
2
3
1

 traversing using nditer
1
2
3
4
2
3
4
6
5
6
7
9
7
4
9
4
3
1
6
5
6
3
4
7
6
8
4
8
6
2
3
1
